from __future__ import annotations

from .contracts import CapabilityDescriptor, CapabilityId, StateAuthority


def _descriptor(
    capability_id: CapabilityId,
    title: str,
    phase: int,
    priority: str,
    dependencies: tuple[CapabilityId, ...],
    *,
    patch_sensitive: bool,
    live_eligible: bool,
    human_review_required: bool,
    summary: str,
    primary_artifacts: tuple[str, ...],
    performance_budget_ms: int | None = None,
) -> CapabilityDescriptor:
    return CapabilityDescriptor(
        capability_id=capability_id,
        title=title,
        phase=phase,
        priority=priority,
        dependencies=dependencies,
        feature_flag=f"science.{capability_id.value}",
        patch_sensitive=patch_sensitive,
        live_eligible=live_eligible,
        human_review_required=human_review_required,
        output_contract="advisory",
        state_authority=StateAuthority.STRATEGIC_OS,
        summary=summary,
        primary_artifacts=primary_artifacts,
        performance_budget_ms=performance_budget_ms,
    )


CAPABILITIES: tuple[CapabilityDescriptor, ...] = (
    _descriptor(
        CapabilityId.FORMAL_INVARIANTS,
        "Formal Rule and Invariant Testing",
        0,
        "P0",
        (),
        patch_sensitive=True,
        live_eligible=False,
        human_review_required=False,
        summary="Generates and checks rule, evidence-boundary, fallback, parity, and cognitive-load invariants.",
        primary_artifacts=("invariant_report", "failing_fixture", "seed"),
    ),
    _descriptor(
        CapabilityId.PROOF_RECOMMENDATIONS,
        "Proof-Carrying Recommendations",
        0,
        "P0",
        (CapabilityId.FORMAL_INVARIANTS,),
        patch_sensitive=True,
        live_eligible=True,
        human_review_required=False,
        summary="Attaches evidence, rules, assumptions, uncertainty, expiration, and fallback to every advisory.",
        primary_artifacts=("proof", "advisory_output"),
        performance_budget_ms=50,
    ),
    _descriptor(
        CapabilityId.DIGITAL_TWIN,
        "Strategic Digital Twin",
        1,
        "P1",
        (CapabilityId.FORMAL_INVARIANTS, CapabilityId.PROOF_RECOMMENDATIONS),
        patch_sensitive=True,
        live_eligible=True,
        human_review_required=False,
        summary="Maintains a lightweight economy, supply, production, prerequisite, technology, and timing simulation.",
        primary_artifacts=("twin_snapshot", "feasibility_envelope", "proof"),
        performance_budget_ms=100,
    ),
    _descriptor(
        CapabilityId.COUNTERFACTUAL_LAB,
        "Counterfactual Decision Lab",
        2,
        "P1",
        (CapabilityId.DIGITAL_TWIN, CapabilityId.PROOF_RECOMMENDATIONS),
        patch_sensitive=True,
        live_eligible=False,
        human_review_required=False,
        summary="Compares alternative decisions from an identical canonical state without claiming certainty.",
        primary_artifacts=("counterfactual_result", "tradeoff_matrix", "proof"),
    ),
    _descriptor(
        CapabilityId.FRAGILITY_ANALYZER,
        "Strategy Fragility Analyzer",
        2,
        "P1",
        (CapabilityId.COUNTERFACTUAL_LAB,),
        patch_sensitive=True,
        live_eligible=False,
        human_review_required=False,
        summary="Measures sensitivity to timing, scouting, unit-loss, and assumption perturbations.",
        primary_artifacts=("fragility_report", "critical_dependency_set"),
    ),
    _descriptor(
        CapabilityId.SYNTHETIC_MATCH_GENERATOR,
        "Synthetic Match Generator",
        2,
        "P1",
        (CapabilityId.DIGITAL_TWIN, CapabilityId.FORMAL_INVARIANTS),
        patch_sensitive=True,
        live_eligible=False,
        human_review_required=False,
        summary="Creates seeded, internally consistent event streams with expected Strategic OS states.",
        primary_artifacts=("synthetic_event_log", "expected_state_trace", "seed"),
    ),
    _descriptor(
        CapabilityId.STRATEGY_DISCOVERY,
        "Automated Strategy Discovery",
        3,
        "P3",
        (
            CapabilityId.DIGITAL_TWIN,
            CapabilityId.FRAGILITY_ANALYZER,
            CapabilityId.PROOF_RECOMMENDATIONS,
        ),
        patch_sensitive=True,
        live_eligible=False,
        human_review_required=True,
        summary="Searches legal strategy space and ranks experimental candidates by mission fit, robustness, novelty, and burden.",
        primary_artifacts=("candidate_policy", "discovery_run", "rejection_log"),
    ),
    _descriptor(
        CapabilityId.SCENARIO_ACADEMY,
        "Procedural Scenario Academy",
        3,
        "P2",
        (CapabilityId.SYNTHETIC_MATCH_GENERATOR, CapabilityId.PROOF_RECOMMENDATIONS),
        patch_sensitive=True,
        live_eligible=False,
        human_review_required=False,
        summary="Generates seeded decision drills with distractors, rubrics, uncertainty, and concept tags.",
        primary_artifacts=("scenario", "answer_rubric", "scenario_seed"),
    ),
    _descriptor(
        CapabilityId.MISCONCEPTION_DETECTOR,
        "Misconception Detector",
        4,
        "P2",
        (CapabilityId.SCENARIO_ACADEMY,),
        patch_sensitive=False,
        live_eligible=False,
        human_review_required=False,
        summary="Produces revisable hypotheses about recurring beliefs behind player decision patterns.",
        primary_artifacts=("misconception_hypothesis", "supporting_observations", "alternative_explanations"),
    ),
    _descriptor(
        CapabilityId.CURRICULUM_PLANNER,
        "Adaptive Curriculum Planner",
        4,
        "P2",
        (CapabilityId.MISCONCEPTION_DETECTOR,),
        patch_sensitive=False,
        live_eligible=False,
        human_review_required=False,
        summary="Selects the next concept, bounded practice block, pass condition, and graduation rule.",
        primary_artifacts=("curriculum_assignment", "concept_graph_path"),
    ),
    _descriptor(
        CapabilityId.KNOWLEDGE_CONFLICT_AUDIT,
        "Knowledge Conflict Auditor",
        4,
        "P2",
        (CapabilityId.PROOF_RECOMMENDATIONS,),
        patch_sensitive=True,
        live_eligible=False,
        human_review_required=True,
        summary="Distinguishes true contradictions from differences in patch, risk, level, map, and assumptions.",
        primary_artifacts=("conflict_report", "claim_cluster", "review_questions"),
    ),
    _descriptor(
        CapabilityId.PATCH_MIGRATION,
        "Patch Migration Compiler",
        4,
        "P2",
        (
            CapabilityId.DIGITAL_TWIN,
            CapabilityId.PROOF_RECOMMENDATIONS,
            CapabilityId.FORMAL_INVARIANTS,
        ),
        patch_sensitive=True,
        live_eligible=False,
        human_review_required=True,
        summary="Finds affected rules and policies, re-simulates them, and classifies current, review, stale, or invalid.",
        primary_artifacts=("migration_report", "affected_artifact_set", "before_after_delta"),
    ),
    _descriptor(
        CapabilityId.STRATEGY_PACK_VALIDATOR,
        "Strategy Pack Validator",
        4,
        "P2",
        (
            CapabilityId.DIGITAL_TWIN,
            CapabilityId.FORMAL_INVARIANTS,
            CapabilityId.PROOF_RECOMMENDATIONS,
        ),
        patch_sensitive=True,
        live_eligible=False,
        human_review_required=True,
        summary="Validates data-only community strategy packs for schema, feasibility, provenance, branches, and fallbacks.",
        primary_artifacts=("pack_validation_report", "quarantined_pack"),
    ),
    _descriptor(
        CapabilityId.TACTICAL_NARRATIVE,
        "Tactical Narrative and SVG Generator",
        5,
        "P2",
        (CapabilityId.PROOF_RECOMMENDATIONS,),
        patch_sensitive=False,
        live_eligible=False,
        human_review_required=False,
        summary="Renders consistent War Room stories, short rationales, timelines, decision trees, and accessible SVGs.",
        primary_artifacts=("narrative_bundle", "sanitized_svg", "text_alternative"),
    ),
    _descriptor(
        CapabilityId.COGNITIVE_OPTIMIZER,
        "Cognitive-Load Optimizer",
        5,
        "P3",
        (CapabilityId.SCENARIO_ACADEMY, CapabilityId.PROOF_RECOMMENDATIONS),
        patch_sensitive=False,
        live_eligible=False,
        human_review_required=True,
        summary="Measures cue burden and recommends timing, wording, modality, ordering, suppression, or silence.",
        primary_artifacts=("cognitive_recommendation", "experiment_report"),
    ),
)


_CAPABILITY_INDEX = {descriptor.capability_id: descriptor for descriptor in CAPABILITIES}


def get_capability(capability_id: CapabilityId | str) -> CapabilityDescriptor:
    normalized = capability_id if isinstance(capability_id, CapabilityId) else CapabilityId(capability_id)
    return _CAPABILITY_INDEX[normalized]
